--21090071_Đặng Lê Hữu Tiến
CREATE DATABASE	QLSach
ON PRIMARY
	(NAME = QLSach_Data,
	FILENAME = 'C:\QLTV\QLSach_Data.mdf',
	SIZE=20MB,
	MAXSIZE=40MB,
	FILEGROWTH=1MB)
LOG ON
	(NAME = QLSach_Log,
	FILENAME = 'C:\QLTV\QLSach_Log.ldf',
	SIZE=6MB,
	MAXSIZE=8MB,
	FILEGROWTH=1MB)

ALTER DATABASE QLSach
ADD FILEGROUP DuLieuSach


ALTER DATABASE QLSach
ADD File (Name = QlSach_Data2,
	Filename= 'C:\QLTV\QlSach_Data2.ndf',
	SIZE=10MB,
	MAXSIZE=20MB) TO FILEGROUP DuLieuSach